-- drop table if exists book cascade;
-- drop table if exists clubber cascade;
-- drop table if exists room cascade;
-- drop table if exists room_clubbers cascade;
-- Do we need that?

create table book
(
    isbn         varchar(255) not null,
    author       varchar(255),
    title        varchar(255),
    description  varchar(255),
    published_at date,
    added_at     timestamp(6) with time zone,
    primary key (isbn)
);

create table clubber
(
    id         bigint generated by default as identity,
    name       varchar(255),
    role       enum ('ADMIN','LIBRARIAN','MEMBER'),
    created_at timestamp(6) with time zone,
    primary key (id)
);

create table room
(
    id                   bigint generated by default as identity,
    name                 varchar(255),
    owner_id             bigint  not null,
    book_id              varchar(255) unique,
    current_chapter      integer not null,
    next_planned_chapter integer not null,
    discussion_board_url varchar(255),
    meeting_url          varchar(255),
    primary key (id)
);

create table room_clubbers
(
    clubber_id bigint not null,
    room_id    bigint not null,
    primary key (clubber_id, room_id)
);


insert into "public"."clubber" ("created_at", "name", "role")
values ('2025-01-31 10:15:00+00', 'Alice Johnson', 'ADMIN'),
       ('2025-01-31 11:30:00+00', 'Bob Smith', 'LIBRARIAN'),
       ('2025-01-31 12:45:00+00', 'Charlie Davis', 'LIBRARIAN'),
       ('2025-01-31 13:00:00+00', 'Diana Green', 'LIBRARIAN'),
       ('2025-01-31 14:20:00+00', 'Ethan White', 'MEMBER'),
       ('2025-01-31 15:35:00+00', 'Fiona Black', 'MEMBER'),
       ('2025-01-31 16:50:00+00', 'George Harris', 'MEMBER'),
       ('2025-01-31 18:05:00+00', 'Hannah Lewis', 'MEMBER'),
       ('2025-01-31 19:20:00+00', 'Ian Walker', 'MEMBER'),
       ('2025-01-31 20:45:00+00', 'Jane Carter', 'MEMBER');


insert into "public"."book" ("isbn", "published_at", "added_at", "author", "title", "description")
values ('978-0132350884', '2008-08-01', '2025-01-31 10:00:00+00', 'Robert C. Martin', 'Clean Code',
        'A handbook of agile software craftsmanship.'),
       ('978-0134494166', '2017-09-20', '2025-01-31 10:05:00+00', 'Robert C. Martin', 'Clean Architecture',
        'A guide to software architecture and design principles.'),
       ('978-0201633610', '1999-10-08', '2025-01-31 10:10:00+00',
        'Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides',
        'Design Patterns: Elements of Reusable Object-Oriented Software', 'The classic book on design patterns.'),
       ('978-0321125217', '2018-11-27', '2025-01-31 10:15:00+00', 'Eric Evans',
        'Domain-Driven Design: Tackling Complexity in the Heart of Software',
        'A deep dive into domain-driven design principles.'),
       ('978-0131177051', '2014-09-25', '2025-01-31 10:20:00+00', 'Michael C. Feathers',
        'Working Effectively with Legacy Code', 'Refactoring legacy code for improved maintainability.');


