<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.codeus</groupId>
    <artifactId>hexagonal-architecture</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>hexagonal-architecture</name>
    <description>Module Hexagonal Architecture</description>
    <packaging>pom</packaging>

    <modules>
        <module>book-club-domain</module>
        <module>book-club-application</module>
        <module>book-club-adapter</module>
        <module>book-club-boot</module>
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.36</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>3.4.2</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>org.codeus</groupId>
                <artifactId>book-club-domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.codeus</groupId>
                <artifactId>book-club-application</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.codeus</groupId>
                <artifactId>book-club-rest</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.codeus</groupId>
                <artifactId>book-club-book-client</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.codeus</groupId>
                <artifactId>book-club-repository</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
