create table if not exists clubber
(
    id         bigint generated by default as identity,
    name       varchar(255),
    role       enum ('ADMIN','LIBRARIAN','MEMBER'),
    created_at timestamp(6),
    primary key (id)
);
